name: CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18'

    - name: Install dependencies for frontend
      run: |
        cd giftlink-frontend
        npm ci

    - name: Build frontend
      run: |
        cd giftlink-frontend
        npm run build
      env:
        CI: false

    - name: Test frontend
      run: |
        cd giftlink-frontend
        npm test

    - name: Install dependencies for backend
      run: |
        cd giftlink-backend
        npm ci

    - name: Test backend
      run: |
        cd giftlink-backend
        npm test

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Build and push frontend Docker image
      uses: docker/build-push-action@v2
      with:
        context: ./giftlink-frontend
        push: false
        tags: giftlink-frontend:latest
        outputs: type=docker,dest=/tmp/frontend-image.tar

    - name: Build and push backend Docker image
      uses: docker/build-push-action@v2
      with:
        context: ./giftlink-backend
        push: false
        tags: giftlink-backend:latest
        outputs: type=docker,dest=/tmp/backend-image.tar

    - name: Install IBM Cloud CLI
      run: |
        curl -fsSL https://clis.cloud.ibm.com/install/linux | sh
        ibmcloud --version
        ibmcloud config --check-version=false
        ibmcloud plugin install -f code-engine

    - name: Authenticate with IBM Cloud CLI
      run: |
        ibmcloud login --apikey "${IBM_CLOUD_API_KEY}" -r "${IBM_CLOUD_REGION}" -g "${IBM_CLOUD_RESOURCE_GROUP}"
        ibmcloud target -r "${IBM_CLOUD_REGION}" -g "${IBM_CLOUD_RESOURCE_GROUP}"
      env:
        IBM_CLOUD_API_KEY: ${{ secrets.IBM_CLOUD_API_KEY }}
        IBM_CLOUD_REGION: ${{ secrets.IBM_CLOUD_REGION }}
        IBM_CLOUD_RESOURCE_GROUP: ${{ secrets.IBM_CLOUD_RESOURCE_GROUP }}

    - name: Deploy to IBM Code Engine
      run: |
        ibmcloud ce project select --name "${CODE_ENGINE_PROJECT}"
        
        # Deploy frontend
        ibmcloud ce application create --name "${FRONTEND_APP_NAME}" --image giftlink-frontend:latest --build-source ./giftlink-frontend --port 80
        
        # Deploy backend
        ibmcloud ce application create --name "${BACKEND_APP_NAME}" --image giftlink-backend:latest --build-source ./giftlink-backend --port 3060
      env:
        CODE_ENGINE_PROJECT: ${{ secrets.CODE_ENGINE_PROJECT }}
        FRONTEND_APP_NAME: ${{ secrets.FRONTEND_APP_NAME }}
        BACKEND_APP_NAME: ${{ secrets.BACKEND_APP_NAME }}

    - name: Get application URLs
      run: |
        FRONTEND_URL=$(ibmcloud ce application get --name "${FRONTEND_APP_NAME}" --output url)
        BACKEND_URL=$(ibmcloud ce application get --name "${BACKEND_APP_NAME}" --output url)
        echo "Frontend is accessible at: ${FRONTEND_URL}"
        echo "Backend is accessible at: ${BACKEND_URL}"
      env:
        FRONTEND_APP_NAME: ${{ secrets.FRONTEND_APP_NAME }}
        BACKEND_APP_NAME: ${{ secrets.BACKEND_APP_NAME }}