name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]  # Specify exact versions if needed

    steps:
      # 1. Checkout the repository
      - uses: actions/checkout@v3

      # 2. Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'  # Enables caching of node modules

      # 3. Verify Frontend Directory Contents
      - name: List Frontend Directory Contents
        run: ls -la giftlink-frontend/

      # 4. Install Frontend Dependencies Using npm ci
      - name: Install Frontend Dependencies
        run: |
          cd giftlink-frontend
          npm ci

      # 5. Build Frontend
      - name: Build Frontend
        run: |
          cd giftlink-frontend
          CI=false npm run build

      # 6. Test Frontend
      - name: Test Frontend
        run: |
          cd giftlink-frontend
          CI=true npm test -- --passWithNoTests

      # 7. Install Backend Dependencies Using npm ci
      - name: Install Backend Dependencies
        run: |
          cd giftlink-backend
          npm ci

      # 8. Test Backend
      - name: Test Backend
        run: |
          cd giftlink-backend
          npm test

      # 9. Build Docker images
      - name: Build Docker images
        run: docker-compose build

      # 10. Run Docker containers
      - name: Run Docker containers
        run: docker-compose up -d

      # 11. Check running containers
      - name: Check running containers
        run: docker ps -a