name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18'

    - name: Install dependencies for frontend
      run: |
        cd giftlink-frontend
        npm ci

    - name: Build frontend
      run: |
        cd giftlink-frontend
        npm run build
      env:
        CI: false

    - name: Test frontend
      run: |
        cd giftlink-frontend
        npm test

    - name: Install dependencies for backend
      run: |
        cd giftlink-backend
        npm ci

    - name: Test backend
      run: |
        cd giftlink-backend
        npm test

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Create Dockerfiles if not exist
      run: |
        # Create frontend Dockerfile if it doesn't exist
        if [ ! -f giftlink-frontend/Dockerfile ]; then
          cat << EOF > giftlink-frontend/Dockerfile
        FROM node:18-alpine AS build
        WORKDIR /app
        COPY package*.json ./
        RUN npm install
        COPY . .
        RUN npm run build
        FROM nginx:stable-alpine
        COPY --from=build /app/build /usr/share/nginx/html
        EXPOSE 80
        CMD ["nginx", "-g", "daemon off;"]
        EOF
        fi

        # Create backend Dockerfile if it doesn't exist
        if [ ! -f giftlink-backend/Dockerfile ]; then
          cat << EOF > giftlink-backend/Dockerfile
        FROM node:18-alpine
        WORKDIR /app
        COPY package*.json ./
        RUN npm install
        COPY . .
        EXPOSE 3060
        CMD ["node", "app.js"]
        EOF
        fi

    - name: Create docker-compose.yml
      run: |
        cat << EOF > docker-compose.yml
        version: '3.8'

        services:
          frontend:
            build:
              context: ./giftlink-frontend
              dockerfile: Dockerfile
            ports:
              - "80:80"
            depends_on:
              - backend

          backend:
            build:
              context: ./giftlink-backend
              dockerfile: Dockerfile
            ports:
              - "3060:3060"
            environment:
              - MONGO_URL=\${MONGO_URL}
            depends_on:
              - mongodb

          mongodb:
            image: mongo:latest
            ports:
              - "27017:27017"
            volumes:
              - mongodb_data:/data/db

        volumes:
          mongodb_data:
        EOF

    - name: Build Docker images
      run: |
        ls -la
        cat docker-compose.yml
        docker compose build

    - name: Run Docker containers
      run: docker compose up -d

    - name: Check running containers
      run: docker ps -a